# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', url: 'about'}
- {name: 'Services', url: 'services'}
- {name: 'Contact', url: 'contact'}

# interim directorships, diversity, equity and inclusion training and coaching,

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/edithqmolina'}
- {icon: 'facebook', link:   'https://www.facebook.com/'}
- {icon: 'instagram', link:  'https://instagram.com/'}
- {icon: 'envelope', link:   'mailto:edith.q.molina@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
